apiVersion: apps/v1
kind: Deployment
metadata:
  name: pris-proj
spec:
  replicas: 3    # Будет создано 3 пода
  selector:
    matchLabels:
      app: pris-proj
  template:
    metadata:
      labels:
        app: pris-proj
      annotations:
        prometheus.io/scrape: "true"  # Разрешаем сбор метрик
        prometheus.io/port: "3000"    # Указываем порт метрик
    spec:
      containers:
      - name: pris-proj
        image: pris-proj:1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"